// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQbuHU0geXU0KIQen-VvaxcHYsjZw3bgI',
    appId: '1:472632052487:web:f791b6685e291a245e53a2',
    messagingSenderId: '472632052487',
    projectId: 'first-app-3a322',
    authDomain: 'first-app-3a322.firebaseapp.com',
    databaseURL: 'https://first-app-3a322-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-3a322.appspot.com',
    measurementId: 'G-740QMZGN9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf1NnUwfPxTZYnJO-OUcv5rFRH1mHOT38',
    appId: '1:472632052487:android:ed9f73efc3144aae5e53a2',
    messagingSenderId: '472632052487',
    projectId: 'first-app-3a322',
    databaseURL: 'https://first-app-3a322-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-3a322.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA59hxGcAAGmHuFxBMXGNIcx12Y89H3XR0',
    appId: '1:472632052487:ios:535db5e53dc03c075e53a2',
    messagingSenderId: '472632052487',
    projectId: 'first-app-3a322',
    databaseURL: 'https://first-app-3a322-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-3a322.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA59hxGcAAGmHuFxBMXGNIcx12Y89H3XR0',
    appId: '1:472632052487:ios:46d57a6680e134b05e53a2',
    messagingSenderId: '472632052487',
    projectId: 'first-app-3a322',
    databaseURL: 'https://first-app-3a322-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-3a322.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
